In [1]:
#importing libraries
import stockLibraries.getStockFinancialDetails as sl
import pandas as pd

Add the NSE tickr or BSE ID in the variable

In [2]:
nse_ticker = "YESBANK"

In [3]:
abbv01 , abbv02 = sl.extract_stock_data(nse_ticker)

Retrieving stock data from money control https://www.moneycontrol.com/mccode/common/autosuggestion_solr.php?classic=true&query=YESBANK&type=1&format=json
Information fetched:
{'link_src': 'https://www.moneycontrol.com/india/stockpricequote/banksprivatesector/yesbank/YB', 'link_track': 'http://arjun.in.com/dashboard/api/profilingSuggestions.php?id=YB&type=stock', 'pdt_dis_nm': 'Yes Bank&nbsp;<span>INE528G01035, YESBANK, 532648</span>', 'sc_id': 'YB', 'stock_name': 'Yes Bank', 'sc_sector_id': 'BF', 'sc_sector': 'Banking & Financial Services'}

## Extract the 3 financial sheets as dataframe

In [4]:
balance_sheet_df = sl.get_financial_sheet(abbv01,abbv02,sl.FINANCIALS.BALANCESHEET)

The url being used to fetch the financial data https://www.moneycontrol.com/financials/yesbank/consolidated-balance-sheetVI/YB#YB

In [5]:
balance_sheet_df

Balance Sheet of Yes Bank (in Rs. Cr.),Mar 20,Mar 19,Mar 18,Mar 17,Mar 16
0,,,,,
EQUITIES AND LIABILITIES,NaN,NaN,NaN,NaN,NaN
SHAREHOLDER'S FUNDS,NaN,NaN,NaN,NaN,NaN
Equity Share Capital,2510.09,463.01,460.59,456.49,420.53
Total Share Capital,2510.09,463.01,460.59,456.49,420.53
Revaluation Reserve,0.00,0.00,0.00,0.00,0.00
Reserves and Surplus,2510.09,463.01,460.59,456.49,420.53
Total Reserves and Surplus,19184.87,26424.40,25291.91,21583.14,13341.85
Total ShareHolders Funds,19184.87,26424.40,25291.91,21583.14,13341.85
Minority Interest,0.00,0.00,0.00,0.00,0.00
Deposits,105311.17,227557.90,200688.60,142857.44,111704.18
Borrowings,113790.50,108424.11,74893.58,38606.67,31658.98
Other Liabilities and Provisions,17035.53,17990.19,11114.96,11555.94,8117.08
Total Capital and Liabilities,257832.16,380859.61,312449.65,215059.69,165242.62
ASSETS,NaN,NaN,NaN,NaN,NaN
Cash and Balances with Reserve Bank of India,5943.66,10797.74,11425.75,6952.07,5776.16
Balances with Banks Money at Call and Short Notice,2486.70,16187.19,13328.07,12602.59,2442.74
Investments,43747.80,89328.53,68293.44,49981.80,48788.47
Advances,171433.09,241397.19,203518.83,132262.68,98209.93
Fixed Assets,1023.38,829.89,837.30,13260.56,474.58
Other Assets,33197.53,22319.07,15046.28,0.00,9550.75
Total Assets,257832.16,380859.61,312449.65,215059.69,165242.62
"CONTINGENT LIABILITIES, COMMITMENTS",NaN,NaN,NaN,NaN,NaN
Bills for Collection,5120.19,5059.24,43104.50,1390.00,27308.95
Contingent Liabilities,458527.53,654161.74,540661.33,379564.57,305489.12

In [7]:
cashflow_df = sl.get_financial_sheet(abbv01,abbv02,sl.FINANCIALS.CASHFLOW)

The url being used to fetch the financial data https://www.moneycontrol.com/financials/yesbank/consolidated-cash-flowVI/YB#YB

In [8]:
cashflow_df

Cash Flow of Yes Bank (in Rs. Cr.),Mar 20,Mar 19,Mar 18,Mar 17,Mar 16
0,,,,,
Net Profit/Loss Before Extraordinary Items And Tax,-20838.19,2349.01,6204.54,5053.47,3756.12
Net CashFlow From Operating Activities,-57721.22,-24573.30,-21810.44,4384.14,-375.62
Net Cash Used In Investing Activities,14191.93,-6293.69,-8744.90,-4473.87,-4022.57
Net Cash Used From Financing Activities,25038.31,33039.32,35747.92,11429.21,5059.70
Foreign Exchange Gains / Losses,-63.59,58.78,6.58,-3.72,0.00
Net Inc/Dec In Cash And Cash Equivalents,-18554.57,2231.11,5199.16,11335.75,661.51
Cash And Cash Equivalents Begin of Year,26984.93,24753.82,19554.66,8218.90,7557.40
Cash And Cash Equivalents End Of Year,8430.36,26984.93,24753.82,19554.66,8218.90

In [9]:
profitloss_df = sl.get_financial_sheet(abbv01,abbv02,sl.FINANCIALS.INCOMESTATEMENT)

The url being used to fetch the financial data https://www.moneycontrol.com/financials/yesbank/consolidated-profit-lossVI/YB#YB

In [10]:
profitloss_df

Profit & Loss account of Yes Bank (in Rs. Cr.),Mar 20,Mar 19,Mar 18,Mar 17,Mar 16
0,,,,,
INCOME,NaN,NaN,NaN,NaN,NaN
Interest / Discount on Advances / Bills,21246.60,22918.54,15477.85,12209.77,9711.48
Income from Investments,4260.92,6048.42,4102.53,3796.84,3508.21
Interest on Balance with RBI and Other Inter-Bank funds,210.37,397.57,516.07,257.82,112.54
Others,334.13,259.26,172.14,160.57,201.21
Total Interest Earned,26052.02,29623.80,20268.59,16425.00,13533.44
Other Income,11956.10,4675.48,5293.15,4217.80,2729.42
Total Income,38008.12,34299.28,25561.75,20642.80,16262.86
EXPENDITURE,NaN,NaN,NaN,NaN,NaN
Interest Expended,19258.06,19811.29,12529.43,10626.53,8965.41
Payments to and Provisions for Employees,2691.32,2538.11,2234.66,1840.24,1319.78
Depreciation,341.93,305.45,232.36,172.61,111.84
Depreciation on Leased Assets,0.00,0.00,0.00,0.00,0.00
Operating Expenses (excludes Employee Cost & Depreciation),3836.89,3517.86,2806.52,2155.77,1573.41
Total Operating Expenses,6870.15,6361.43,5273.54,4168.61,3005.03
Provision Towards Income Tax,0.00,2300.97,2243.92,1839.55,1348.76
Provision Towards Deferred Tax,0.00,-1661.23,-272.60,-125.97,-122.33
Other Provisions and Contingencies,28312.49,5777.56,1554.24,794.19,536.30
Total Provisions and Contingencies,28312.49,6417.30,3525.56,2507.78,1762.73
Total Expenditure,54440.70,32590.01,21328.53,17302.91,13733.18
Net Profit / Loss for The Year,-16432.58,1709.27,4233.22,3339.89,2529.69
Net Profit / Loss After EI & Prior Year Items,-16432.58,1709.27,4233.22,3339.89,2529.69
Minority Interest,0.00,0.00,0.00,0.00,0.00
Share Of Profit/Loss Of Associates,0.00,0.00,0.00,0.00,0.00
Consolidated Profit/Loss After MI And Associates,-16432.58,1709.27,4233.22,3339.89,2529.69
Profit / Loss Brought Forward,10742.77,10369.53,7918.96,5520.46,4205.59
Total Profit / Loss available for Appropriations,-5689.81,12078.80,12152.18,8860.35,6735.28
APPROPRIATIONS,NaN,NaN,NaN,NaN,NaN
Transfer To / From Statutory Reserve,0.00,430.07,1056.14,832.52,634.86
Transfer To / From Revenue And Other Reserves,0.00,53.91,0.00,0.00,0.00
Dividend and Dividend Tax for The Previous Year,558.64,750.36,0.00,0.56,0.32
Equity Share Dividend,0.00,0.00,548.81,0.00,420.53
Tax On Dividend,0.00,0.00,111.74,0.00,85.62
Balance Carried Over To Balance Sheet,-6928.72,10742.77,10369.53,7918.96,5520.46
Total Appropriations,-5689.81,12078.80,12152.18,8860.35,6735.28
OTHER ADDITIONAL INFORMATION,NaN,NaN,NaN,NaN,NaN
EARNINGS PER SHARE,NaN,NaN,NaN,NaN,NaN
Basic EPS (Rs.),-56.00,7.00,18.00,79.00,60.00
Diluted EPS (Rs.),-56.00,7.00,18.00,77.00,59.00

In [11]:
quit()